Consent Modal (DEV-642)
BetterAngelsLA/monorepo pull request #538
Opened 2024-08-29 17:00 UTC by davelindqvist

[DEV-642](https://betterangels.atlassian.net/browse/DEV-642?atlOrigin=eyJpIjoiNTNhNzg0ZjBlYTI1NGI5M2E1NTAxMGFiMTkwM2M2YzQiLCJwIjoiaiJ9)

NOTE: The iPad styling is quite off. Unsure how to approach this, but at least it covers up the clients.
<img width="829" alt="image" src="https://github.com/user-attachments/assets/90b179e5-d058-4148-b05a-cdda36e5ff08">

2024-09-05 21:12 UTC, Davit-BetterAngels commented on apps/betterangels/src/app/(tabs)/_layout.tsx
> +        height={'90%'}
I would rather do only offset from top or offset + what ui needs. 
90% will look different from device to device. 

const insets = useSafeAreaInsets();
const topOffset = insets.top;

2024-09-05 21:23 UTC, shiozakiyuko commented
Hey @davelindqvist and @Davit-BetterAngels 
I can create a ticket for tablet issue since we are not dealing with this currently so you guys can move on.
I think we will plan to deal with it in Oct.

2024-09-05 21:40 UTC, Davit-BetterAngels commented
border radius of the modal is wrong. not 24.

2024-09-05 21:41 UTC, Davit-BetterAngels commented
<img width="362" alt="Screenshot 2024-09-05 at 2 41 14 PM" src="https://github.com/user-attachments/assets/a9fd902f-5852-44a0-abe8-f70a8aa78975">
broken on small screen

2024-09-05 21:47 UTC, Davit-BetterAngels requested changes

2024-09-05 21:47 UTC, Davit-BetterAngels commented on libs/expo/betterangels/src/lib/ui-components/ConsentModal.tsx
> +    position: 'absolute',
bad idea to put under absolute

2024-09-05 21:47 UTC, Davit-BetterAngels commented on libs/expo/betterangels/src/lib/ui-components/ConsentModal.tsx
> +              marginTop: '10%',
we should not differ position of the image based on the device from top unless it is required.

2024-09-09 21:56 UTC, Davit-BetterAngels approved these changes

2024-09-10 20:12 UTC, shiozakiyuko commented
It works as expected. Thanks so much!

One question. Out of curiosity, is there any way to make the image less fuzzy? 
I thought it's my vision but I asked my team and they also see it a little fuzzy.

Let me know if you can make it better. Thanks!

2024-09-10 20:25 UTC, shiozakiyuko commented
Hi @davelindqvist ,

Please use this SVG file for the image.

Figma link for [the Sign Up frame](https://www.figma.com/design/waIeX8dknHKedTrVxCQAAG/HIFI---1st-MVPs?node-id=14537-86956&t=lhFrx8cXThijlExz-4)

Figma link for the [SVG file](https://www.figma.com/design/waIeX8dknHKedTrVxCQAAG/HIFI---1st-MVPs?node-id=15483-306890&t=lhFrx8cXThijlExz-4)

Thanks so much!

2024-09-11 21:22 UTC, shiozakiyuko commented
Hi @davelindqvist 
I just tested this and looks wonderful! Thanks so much!

2024-09-11 23:33 UTC, shiozakiyuko commented
Hey @davelindqvist ,

I reviewed on both iOS and Android. They all look great! Thanks so much!

2024-09-11 23:33 UTC, shiozakiyuko approved these changes

2024-09-12 16:56 UTC, merged