Interaction document upload backend (DEV-855)
BetterAngelsLA/monorepo pull request #699
Opened 2024-11-12 03:34 UTC by mikefeldberg

DEV-855

2024-11-12 20:55 UTC, mikefeldberg commented on apps/betterangels-backend/clients/schema.py
> +            permission_group = get_user_permission_group(user)
this is just a lil refactor. I moved permission checks to the top of any op they were in

2024-11-12 22:11 UTC, vecchp commented on apps/betterangels-backend/clients/types.py
> +    note_id: Optional[ID]
Not a fan of leaking note information into the client app

2024-11-13 21:04 UTC, vecchp requested changes
The current approach is problematic as it retrieves an unrestricted number of documents each time the client profile loads, which could lead to performance issues as we scale. We should instead use a dedicated document endpoint with pagination capabilities.

We need to create a ticket to replace these model properties with paginated endpoints. Once the ticket is created, we can reference it here and proceed with the merge. This change should be prioritized since it’s a quick fix that addresses a potential scalability issue.

2025-01-16 16:53 UTC, mikefeldberg commented
this was a quick and dirty implementation of something that's no longer urgent and should be redone with pagination when we have the time

2025-01-16 16:53 UTC, closed without merging